name: risk311
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0
  - attrs=25.4.0
  - blosc=1.21.6
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - certifi=2025.11.12
  - click=8.3.1
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - colorama=0.4.6
  - freexl=2.0.0
  - gdal=3.12.1
  - geos=3.14.1
  - icu=78.1
  - krb5=1.21.3
  - lerc=4.0.0
  - libarchive=3.8.2
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcurl=8.17.0
  - libdeflate=1.25
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgdal-core=3.12.1
  - libhwloc=2.12.1
  - libhwy=1.3.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.1
  - libkml=1.3.0
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libpng=1.6.53
  - librttopo=1.1.0
  - libspatialite=5.1.0
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxml2-devel=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - lz4-c=1.10.0
  - lzo=2.10
  - minizip=4.0.10
  - mkl=2025.3.0
  - muparser=2.3.5
  - openssl=3.6.0
  - pandas=2.3.3
  - pcre2=10.47
  - pip=25.3
  - proj=9.7.1
  - pyparsing=3.3.1
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.3
  - python_abi=3.11
  - pytz=2025.2
  - rasterio=1.4.4
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - snuggs=1.4.7
  - sqlite=3.51.1
  - tbb=2022.3.0
  - tk=8.6.13
  - tzdata=2025c
  - ucrt=10.0.26100.0
  - uriparser=0.9.8
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - wheel=0.45.1
  - xerces-c=3.3.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - anyio==4.12.0
      - asgiref==3.11.0
      - asteval==1.0.8
      - astunparse==1.6.3
      - blinker==1.9.0
      - boto3==1.42.19
      - botocore==1.42.19
      - bw-migrations==0.2
      - bw-processing==1.0
      - bw2calc==2.3
      - bw2data==4.5.4
      - bw2io==0.9.13
      - bw2parameters==1.1.0
      - cached-property==2.0.1
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - constructive-geometries==1.0
      - country-converter==1.3.2
      - dataflows-tabulator==1.54.3
      - datapackage==1.15.4
      - deepdiff==7.0.1
      - deprecated==1.3.1
      - django==5.2.9
      - django-filter==25.2
      - django-leaflet==0.33.0
      - django-taggit==6.1.0
      - django-unfold==0.74.1
      - djangorestframework==3.16.1
      - djangorestframework-gis==1.2.0
      - docopt==0.6.2
      - et-xmlfile==2.0.0
      - flexcache==0.3
      - flexparser==0.4
      - fsspec==2025.12.0
      - googletrans==4.0.2
      - greenlet==3.3.0
      - h11==0.16.0
      - h2==4.3.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - hyperframe==6.1.0
      - idna==3.11
      - ijson==3.4.0.post0
      - isodate==0.7.2
      - jmespath==1.0.1
      - joblib==1.5.3
      - jsonlines==4.0.0
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - leaflet==0.0.3
      - linear-tsv==1.1.0
      - llvmlite==0.46.0
      - loguru==0.7.3
      - lxml==6.0.2
      - matrix-utils==0.6.2
      - morefs==0.2.2
      - mrio-common-metadata==0.2.1
      - numba==0.63.1
      - numpy==1.26.4
      - openpyxl==3.1.5
      - ordered-set==4.1.0
      - packaging==25.0
      - peewee==3.18.3
      - pillow==12.0.0
      - pint==0.25.2
      - platformdirs==4.5.1
      - prettytable==3.17.0
      - psycopg2-binary==2.9.11
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pyecospold==4.0.0
      - pyprind==2.11.3
      - python-decouple==3.8
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - pyxlsb==1.0.10
      - pyyaml==6.0.3
      - randonneur==0.7.2
      - randonneur-data==0.7.2
      - rapidfuzz==3.14.3
      - rdflib==7.5.0
      - referencing==0.37.0
      - reportlab==4.4.3
      - requests==2.32.5
      - rfc3986==2.0.0
      - rpds-py==0.30.0
      - s3transfer==0.16.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sniffio==1.3.1
      - snowflake-id==1.0.2
      - sparqlwrapper==2.0.0
      - sparse==0.17.0
      - sqlalchemy==2.0.45
      - sqlparse==0.5.5
      - stats-arrays==1.0
      - structlog==25.5.0
      - tableschema==1.21.0
      - threadpoolctl==3.6.0
      - toolz==1.1.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - unfold==1.2.4
      - unicodecsv==0.14.1
      - urllib3==2.6.2
      - voluptuous==0.16.0
      - wcwidth==0.2.14
      - win32-setctime==1.2.0
      - wrapt==2.0.1
      - wurst==0.5.3
      - xarray==2025.12.0
      - xlrd==2.0.2
      - xlsxwriter==3.2.9
prefix: C:\Users\krishna\miniconda3\envs\risk311
