name: risk311
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0=pyhd8ed1ab_1
  - attrs=25.4.0=pyhcf101f3_1
  - blosc=1.21.6=hfd34d9b_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - click=8.3.1=pyha7b4d00_1
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_1
  - freexl=2.0.0=hf297d47_2
  - gdal=3.12.1=py311ha7b5f94_0
  - geos=3.14.1=hdade9fe_0
  - icu=78.1=h637d24d_0
  - krb5=1.21.3=hdf4eb48_0
  - lerc=4.0.0=h6470a55_1
  - libarchive=3.8.2=gpl_h26aea39_100
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libcurl=8.17.0=h43ecb02_1
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libgdal-core=3.12.1=h4c6072a_0
  - libhwloc=2.12.1=default_h4379cf1_1003
  - libhwy=1.3.0=ha71e874_1
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=3.1.2=hfd05255_0
  - libjxl=0.11.1=hac9b6f3_5
  - libkml=1.3.0=h68a222c_1022
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libpng=1.6.53=h7351971_0
  - librttopo=1.1.0=haa95264_20
  - libspatialite=5.1.0=gpl_h0cd62ae_119
  - libsqlite=3.51.1=hf5d6505_1
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.1=h8f73337_1
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.15.1=h779ef1b_1
  - libxml2-16=2.15.1=h3cfd58e_1
  - libxml2-devel=2.15.1=h779ef1b_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.8=h4fa8253_0
  - lz4-c=1.10.0=h2466b09_1
  - lzo=2.10=h6a83c73_1002
  - minizip=4.0.10=h9fa1bad_0
  - mkl=2025.3.0=hac47afa_454
  - muparser=2.3.5=he0c23c2_0
  - openssl=3.6.0=h725018a_0
  - pandas=2.3.3=py311h11fd7f3_2
  - pcre2=10.47=hd2b5f0e_0
  - pip=25.3=pyh8b19718_0
  - proj=9.7.1=h7b1ce8f_0
  - pyparsing=3.3.1=pyhcf101f3_0
  - python=3.11.14=h0159041_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - rasterio=1.4.4=py311h54359c7_2
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_1
  - snuggs=1.4.7=pyhd8ed1ab_2
  - sqlite=3.51.1=hdb435a2_1
  - tbb=2022.3.0=hd094cb3_1
  - tk=8.6.13=h2c6b04d_3
  - tzdata=2025c=hc9c84f9_1
  - ucrt=10.0.26100.0=h57928b3_0
  - uriparser=0.9.8=h5a68840_0
  - vc=14.3=h2b53caa_33
  - vc14_runtime=14.44.35208=h818238b_33
  - vcomp14=14.44.35208=h818238b_33
  - wheel=0.45.1=pyhd8ed1ab_1
  - xerces-c=3.3.0=hac47afa_1
  - zlib=1.3.1=h2466b09_2
  - zstd=1.5.7=h534d264_6
  - pip:
      - annotated-types==0.7.0
      - anyio==4.12.0
      - asgiref==3.11.0
      - asteval==1.0.8
      - astunparse==1.6.3
      - blinker==1.9.0
      - boto3==1.42.19
      - botocore==1.42.19
      - bw-migrations==0.2
      - bw-processing==1.0
      - bw2calc==2.3
      - bw2data==4.5.4
      - bw2io==0.9.13
      - bw2parameters==1.1.0
      - cached-property==2.0.1
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - constructive-geometries==1.0
      - country-converter==1.3.2
      - dataflows-tabulator==1.54.3
      - datapackage==1.15.4
      - deepdiff==7.0.1
      - deprecated==1.3.1
      - django==5.2.9
      - django-filter==25.2
      - django-leaflet==0.33.0
      - django-taggit==6.1.0
      - django-unfold==0.74.1
      - djangorestframework==3.16.1
      - djangorestframework-gis==1.2.0
      - docopt==0.6.2
      - et-xmlfile==2.0.0
      - flexcache==0.3
      - flexparser==0.4
      - fsspec==2025.12.0
      - googletrans==4.0.2
      - greenlet==3.3.0
      - h11==0.16.0
      - h2==4.3.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - hyperframe==6.1.0
      - idna==3.11
      - ijson==3.4.0.post0
      - isodate==0.7.2
      - jmespath==1.0.1
      - joblib==1.5.3
      - jsonlines==4.0.0
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - leaflet==0.0.3
      - linear-tsv==1.1.0
      - llvmlite==0.46.0
      - loguru==0.7.3
      - lxml==6.0.2
      - matrix-utils==0.6.2
      - morefs==0.2.2
      - mrio-common-metadata==0.2.1
      - numba==0.63.1
      - numpy==1.26.4
      - openpyxl==3.1.5
      - ordered-set==4.1.0
      - packaging==25.0
      - peewee==3.18.3
      - pillow==12.0.0
      - pint==0.25.2
      - platformdirs==4.5.1
      - prettytable==3.17.0
      - psycopg2-binary==2.9.11
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pyecospold==4.0.0
      - pyprind==2.11.3
      - python-decouple==3.8
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - pyxlsb==1.0.10
      - pyyaml==6.0.3
      - randonneur==0.7.2
      - randonneur-data==0.7.2
      - rapidfuzz==3.14.3
      - rdflib==7.5.0
      - referencing==0.37.0
      - reportlab==4.4.3
      - requests==2.32.5
      - rfc3986==2.0.0
      - rpds-py==0.30.0
      - s3transfer==0.16.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sniffio==1.3.1
      - snowflake-id==1.0.2
      - sparqlwrapper==2.0.0
      - sparse==0.17.0
      - sqlalchemy==2.0.45
      - sqlparse==0.5.5
      - stats-arrays==1.0
      - structlog==25.5.0
      - tableschema==1.21.0
      - threadpoolctl==3.6.0
      - toolz==1.1.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - unfold==1.2.4
      - unicodecsv==0.14.1
      - urllib3==2.6.2
      - voluptuous==0.16.0
      - wcwidth==0.2.14
      - win32-setctime==1.2.0
      - wrapt==2.0.1
      - wurst==0.5.3
      - xarray==2025.12.0
      - xlrd==2.0.2
      - xlsxwriter==3.2.9
prefix: C:\Users\krishna\miniconda3\envs\risk311
